spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zjt
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    #设置字符编码
    encoding:
      enabled: true
      charset: utf-8
      force: true
    context-path: /crm
